import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="md:grid md:grid-cols-[1fr_2fr_1fr] md:gap-5 md:min-h-screen">
          {/* 左カラム */}
          <div>
            <Header />
          </div>
          {/* 中央カラム */}
          <main>{children}</main>
          {/* 右カラム */}
          <div></div>
        </div>
      </body>
    </html>
  );
}
